export const FETCH_MOVIES = 'FETCH_MOVIES';

export const FILTER_BY_DIRECTOR = 'FILTER_BY_DIRECTOR';
export const FILTER_BY_GENRE = 'FILTER_BY_GENRE';
export const FILTER_BY_ACTOR = 'FILTER_BY_ACTOR';
export const FILTER_BY_FREETEXT = 'FILTER_BY_FREETEXT';
export const FILTER_BY_BOOKMARKS = 'FILTER_BY_BOOKMARKS';
export const RESET_FILTER = 'RESET_FILTER';

export const SET_SORT_ORDER = 'SET_SORT_ORDER';

export const ADD_BOOKMARK = 'ADD_BOOKMARK';
export const REMOVE_BOOKMARK = 'REMOVE_BOOKMARK';
